// Opens a SQLCipher-encrypted better-sqlite3-multiple-ciphers connection.
//
// Required env (validated by ensureKeys()):
//   KDTU_DB_KEY      >= 32 chars  -> passed straight to SQLCipher
//   KDTU_FIELD_KEY   >= 32 chars  -> used by utils/crypto.js (SHA-256 -> 32B AES key)
//   KDTU_JWT_SECRET  any non-empty
//
// On first run, if .env is missing, generate random keys into .env (mode 0600)
// and log a loud warning. Tests pass deterministic keys via env.
import Database from 'better-sqlite3-multiple-ciphers'
import { existsSync, readFileSync, writeSync, openSync, chmodSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { randomBytes } from 'node:crypto'
import { applySchema } from './migrate.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const SERVER_ROOT = join(__dirname, '..', '..')
const ENV_PATH = join(SERVER_ROOT, '.env')

let _db = null

const MIN_KEY_LEN = 32

export function ensureKeys() {
  // Load existing .env into process.env so DB_KEY/FIELD_KEY/JWT_SECRET are visible.
  if (existsSync(ENV_PATH)) {
    const text = readFileSync(ENV_PATH, 'utf8')
    for (const line of text.split(/\r?\n/)) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/)
      if (!m) continue
      const [, k, v] = m
      if (process.env[k] === undefined) process.env[k] = v
    }
  }

  let generated = false
  for (const k of ['KDTU_DB_KEY', 'KDTU_FIELD_KEY', 'KDTU_JWT_SECRET']) {
    const v = process.env[k]
    if (typeof v === 'string' && v.length >= MIN_KEY_LEN) continue
    // Generate. Use base64 so random bytes map to > 32 chars even for low-entropy fields.
    process.env[k] = randomBytes(48).toString('base64')
    generated = true
  }

  if (generated) {
    const fd = openSync(ENV_PATH, 'a')
    try {
      const lines =
        '\n' +
        `# Auto-generated by server on ${new Date().toISOString()} — DO NOT COMMIT\n` +
        `KDTU_DB_KEY=${process.env.KDTU_DB_KEY}\n` +
        `KDTU_FIELD_KEY=${process.env.KDTU_FIELD_KEY}\n` +
        `KDTU_JWT_SECRET=${process.env.KDTU_JWT_SECRET}\n`
      writeSync(fd, lines)
    } finally {
      // fd stays open until close; do best-effort close via sync handle.
      try { require('node:fs').closeSync(fd) } catch {}
    }
    try { chmodSync(ENV_PATH, 0o600) } catch {}
    console.warn('[db] WARN: generated KDTU_* keys into .env (mode 0600). Replace before deploying.')
  }

  // Fail loudly on too-short keys (e.g. someone set them to "dev").
  for (const k of ['KDTU_DB_KEY', 'KDTU_FIELD_KEY', 'KDTU_JWT_SECRET']) {
    const v = process.env[k]
    if (!v || v.length < MIN_KEY_LEN) {
      throw new Error(`[db] FATAL: ${k} must be set and >= ${MIN_KEY_LEN} chars. Refusing to start.`)
    }
  }
}

export function openDb({ dbKey, inMemory = false } = {}) {
  if (_db) return _db
  if (!dbKey) {
    ensureKeys()
    dbKey = process.env.KDTU_DB_KEY
  }
  if (!dbKey || dbKey.length < MIN_KEY_LEN) {
    throw new Error('[db] FATAL: KDTU_DB_KEY must be set and >= 32 chars. Refusing to start.')
  }

  const filename = inMemory ? ':memory:' : (process.env.KDTU_DB_FILE || join(SERVER_ROOT, 'data', 'kdtu.db'))
  const db = new Database(filename)
  // SQLCipher setup MUST happen before any prepare/exec.
  db.pragma("cipher='sqlcipher'")
  db.pragma(`key="${dbKey.replace(/"/g, '""')}"`)
  // Pragmas that improve encrypted DB behaviour.
  db.pragma('journal_mode = WAL')
  db.pragma('foreign_keys = ON')

  applySchema(db)
  _db = db
  return db
}

export function closeDb() {
  if (_db) {
    try { _db.close() } catch {}
    _db = null
  }
}

export function getDb() {
  if (!_db) throw new Error('[db] getDb() called before openDb()')
  return _db
}